const bestiary = [
    {
        id: 'lesserGoblin',
        name: 'Lesser Goblin',
        stats: {
            hp: 5,
            melee: 25,
            ranged: 25,
            dexterity: 24,
            strength: 2,
            thoughtness: 2,
            speed: 4,
            initiative: 40,
            attacks: 1,
            inteligence: 18,
            willpower: 18,
            charisma: 18,
        },
        level: 1,
        type: 'humanoid',
        loot: 'goblin',
        weapon: null,
        description:
            'Goblins are by far the most common of the goblinoid races (i.e., lesser Goblins, Hobgoblins, Orcs, Black Orcs, and Snotlings). They love to inflict pain and suffering on other creatures, and squabble amongst themselves if they have no one else to fight. Lacking fighting discipline, they make very poor warriors and often run away at the first opportunity. In spite of their numbers, Goblins are so disunited and undisciplined that they rarely present anything other than a transitory threat to Human settlements. Their favorite mounts are Wolves or Boars.',
    },
    {
        id: 'goblin',
        name: 'Goblin',
        stats: {
            hp: 7,
            melee: 25,
            ranged: 25,
            dexterity: 18,
            strength: 3,
            thoughtness: 3,
            speed: 4,
            initiative: 20,
            attacks: 1,
            inteligence: 18,
            willpower: 18,
            charisma: 18,
        },
        level: 1,
        type: 'humanoid',
        loot: 'goblin',
        weapon: null,
        description:
            'Goblins are by far the most common of the goblinoid races (i.e., lesser Goblins, Hobgoblins, Orcs, Black Orcs, and Snotlings). They love to inflict pain and suffering on other creatures, and squabble amongst themselves if they have no one else to fight. Lacking fighting discipline, they make very poor warriors and often run away at the first opportunity. In spite of their numbers, Goblins are so disunited and undisciplined that they rarely present anything other than a transitory threat to Human settlements. Their favorite mounts are Wolves or Boars.',
    },
    {
        id: 'orc',
        name: 'Orc',
        stats: {
            hp: 7,
            melee: 33,
            ranged: 25,
            dexterity: 29,
            strength: 3,
            thoughtness: 4,
            speed: 4,
            initiative: 20,
            attacks: 1,
            inteligence: 29,
            willpower: 29,
            charisma: 18,
        },
        level: 2,
        type: 'humanoid',
        weapon: null,
        description:
            'Orcs are powerful warriors - the toughest of the goblinoid races - and often install themselves as leaders of their weaker cousins. They are repulsive monsters who love inflicting pain and delight in cruelty and slaughter. Orcs are always fighting and, if they cannot find enemies to fight, they will fight each other. The whole of Orc technology and culture is geared towards conflict. They are dangerous individual foes, but lack the organisation or motivation to present any real long-term threat to humanity. Orcs speak the common Goblin tongue, usually about four octaves lower than any Goblin.',
    },
    {
        id: 'ogr',
        name: 'Ogr',
        stats: {
            hp: 17,
            melee: 33,
            ranged: 17,
            dexterity: 18,
            strength: 4,
            thoughtness: 5,
            speed: 6,
            initiative: 30,
            attacks: 2,
            inteligence: 14,
            willpower: 29,
            charisma: 10,
        },
        level: 3,
        type: 'humanoid',
        weapon: null,
        description:
            'Ogres are gross, ugly humanoids who love to fight and kill. However, they are not particularly discriminating and will hire their services out to the higest bidder. They are not an overly cruel race, but they are brutal and have little respect for the weak or helpless.',
    },
    {
        id: 'skeleton',
        name: 'Skeleton',
        stats: {
            hp: 5,
            melee: 25,
            ranged: 17,
            dexterity: 18,
            strength: 3,
            thoughtness: 3,
            speed: 4,
            initiative: 20,
            attacks: 1,
            inteligence: 18,
            willpower: 18,
            charisma: 0,
        },
        level: 1,
        type: 'humanoid',
        weapon: null,
        description:
            'A Skeleton is magically formed from the remains of a long-dead humanoid. Skeletons lack strong wills of their own and are sustained only by magic.',
    },
    {
        id: 'liche',
        name: 'Liche',
        stats: {
            hp: 25,
            melee: 41,
            ranged: 25,
            dexterity: 45,
            strength: 4,
            thoughtness: 4,
            speed: 4,
            initiative: 60,
            attacks: 4,
            inteligence: 89,
            willpower: 89,
            charisma: 0,
        },
        level: 3,
        type: 'humanoid',
        weapon: null,
        description:
            'Liches are Undead Necromancers. They have become foul, twisted, and tormented by years of evil toil. Their mental and bodily functions are preserved by powerful magic, but their bodies continue to decompose as if they were truly dead.',
    },
]

export { bestiary }
